"""update depositor

Revision ID: 29967a956f22
Revises: fd4ae9ea1aec
Create Date: 2022-04-04 21:23:13.790472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29967a956f22'
down_revision = 'fd4ae9ea1aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cdp', sa.Column('depositor_pre', sa.String(), nullable=False))
    op.add_column('cdp', sa.Column('depositor_suf', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cdp', 'depositor_suf')
    op.drop_column('cdp', 'depositor_pre')
    # ### end Alembic commands ###
