"""add phone to users

Revision ID: 9416e779df37
Revises: 94810f0d8e8c
Create Date: 2022-03-31 23:17:57.016147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9416e779df37"
down_revision = "94810f0d8e8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
