"""fix CDP name

Revision ID: fd4ae9ea1aec
Revises: acb7f0961bac
Create Date: 2022-04-03 22:27:19.426764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fd4ae9ea1aec"
down_revision = "acb7f0961bac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cdp",
        sa.Column("STT", sa.Integer(), nullable=False),
        sa.Column("depositor", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("published", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("STT"),
    )
    op.drop_table("CDP")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "CDP",
        sa.Column(
            "STT",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"CDP_STT_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("depositor", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "published",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("STT", name="CDP_pkey"),
    )
    op.drop_table("cdp")
    # ### end Alembic commands ###
